#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent for e-menum.net QR Menu SaaS
# Date: 2026-01-13

set -e

echo "========================================"
echo "e-menum.net Development Environment Setup"
echo "========================================"
echo ""

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

# Project root
PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$PROJECT_ROOT"

echo -e "${BLUE}Project Root:${NC} $PROJECT_ROOT"
echo ""

# Check prerequisites
echo -e "${YELLOW}Checking prerequisites...${NC}"

# Check Node.js
if ! command -v node &> /dev/null; then
    echo -e "${RED}Node.js is not installed. Please install Node.js >= 20.9${NC}"
    exit 1
fi

NODE_VERSION=$(node -v | cut -d'v' -f2 | cut -d'.' -f1)
if [ "$NODE_VERSION" -lt 20 ]; then
    echo -e "${RED}Node.js version must be >= 20.9. Current: $(node -v)${NC}"
    exit 1
fi
echo -e "${GREEN}Node.js:${NC} $(node -v)"

# Check npm
if ! command -v npm &> /dev/null; then
    echo -e "${RED}npm is not installed${NC}"
    exit 1
fi
echo -e "${GREEN}npm:${NC} $(npm -v)"

# Check if Supabase CLI is installed (optional for local dev)
if command -v supabase &> /dev/null; then
    echo -e "${GREEN}Supabase CLI:${NC} $(supabase --version)"
else
    echo -e "${YELLOW}Supabase CLI not installed (optional for local dev)${NC}"
fi

echo ""

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo -n "Waiting for $name on port $port..."
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e " ${RED}FAILED${NC}"
            echo -e "${RED}$name failed to start within ${max}s${NC}"
            return 1
        fi
        echo -n "."
        sleep 1
    done
    echo -e " ${GREEN}READY${NC}"
}

# ============================================
# INSTALL DEPENDENCIES
# ============================================

echo -e "${YELLOW}Installing dependencies...${NC}"

if [ ! -d "node_modules" ]; then
    npm install
    echo -e "${GREEN}Dependencies installed${NC}"
else
    echo -e "${GREEN}Dependencies already installed${NC}"
fi

echo ""

# ============================================
# ENVIRONMENT SETUP
# ============================================

echo -e "${YELLOW}Checking environment variables...${NC}"

if [ ! -f ".env.local" ]; then
    if [ -f ".env.local.example" ]; then
        echo -e "${YELLOW}Creating .env.local from example...${NC}"
        cp .env.local.example .env.local
        echo -e "${RED}Please update .env.local with your Supabase credentials${NC}"
        echo ""
        echo "Required variables:"
        echo "  NEXT_PUBLIC_SUPABASE_URL=<your-supabase-url>"
        echo "  NEXT_PUBLIC_SUPABASE_ANON_KEY=<your-anon-key>"
        echo "  SUPABASE_SERVICE_ROLE_KEY=<your-service-role-key>"
        echo "  SITE_URL=http://localhost:3000"
        echo ""
    else
        echo -e "${RED}.env.local not found and no example file exists${NC}"
        echo "Please create .env.local with Supabase credentials"
    fi
else
    echo -e "${GREEN}.env.local exists${NC}"
fi

echo ""

# ============================================
# DATABASE SETUP (LOCAL SUPABASE)
# ============================================

echo -e "${YELLOW}Database setup...${NC}"

if command -v supabase &> /dev/null; then
    echo "Supabase CLI detected. Starting local Supabase..."

    # Check if Supabase is already running
    if supabase status 2>/dev/null | grep -q "API URL"; then
        echo -e "${GREEN}Local Supabase already running${NC}"
    else
        echo "Starting local Supabase (this may take a minute)..."
        supabase start &
        SUPABASE_PID=$!

        # Wait for Supabase to be ready
        wait_for_service 54321 "Supabase API"
        wait_for_service 54322 "Supabase DB"
    fi

    # Apply migrations if they exist
    if [ -d "supabase/migrations" ] && [ "$(ls -A supabase/migrations 2>/dev/null)" ]; then
        echo -e "${YELLOW}Applying database migrations...${NC}"
        supabase db push || echo -e "${YELLOW}Some migrations may already be applied${NC}"
        echo -e "${GREEN}Migrations applied${NC}"
    fi
else
    echo -e "${YELLOW}Supabase CLI not installed. Using remote Supabase.${NC}"
    echo "Make sure your .env.local points to a valid Supabase project."
fi

echo ""

# ============================================
# START NEXT.JS DEVELOPMENT SERVER
# ============================================

echo -e "${YELLOW}Starting Next.js development server...${NC}"

# Start in background if requested
if [ "$1" == "--background" ]; then
    npm run dev &
    NEXTJS_PID=$!

    wait_for_service 3000 "Next.js"

    echo ""
    echo "========================================"
    echo -e "${GREEN}Environment Ready!${NC}"
    echo "========================================"
    echo ""
    echo "Services:"
    echo -e "  Next.js App:     ${BLUE}http://localhost:3000${NC}"
    if command -v supabase &> /dev/null; then
        echo -e "  Supabase Studio: ${BLUE}http://localhost:54323${NC}"
        echo -e "  Supabase API:    ${BLUE}http://localhost:54321${NC}"
    fi
    echo ""
    echo "Key URLs:"
    echo -e "  Landing Page:    ${BLUE}http://localhost:3000/${NC}"
    echo -e "  Login:           ${BLUE}http://localhost:3000/login${NC}"
    echo -e "  Dashboard:       ${BLUE}http://localhost:3000/dashboard${NC}"
    echo -e "  Public Menu:     ${BLUE}http://localhost:3000/menu/[slug]${NC}"
    echo ""
    echo "To stop services:"
    echo "  pkill -f 'next dev'"
    echo "  supabase stop (if using local Supabase)"
    echo ""
else
    echo ""
    echo "========================================"
    echo -e "${GREEN}Environment Ready!${NC}"
    echo "========================================"
    echo ""
    echo "Services:"
    echo -e "  Next.js App:     ${BLUE}http://localhost:3000${NC}"
    if command -v supabase &> /dev/null; then
        echo -e "  Supabase Studio: ${BLUE}http://localhost:54323${NC}"
        echo -e "  Supabase API:    ${BLUE}http://localhost:54321${NC}"
    fi
    echo ""
    echo "Starting Next.js in foreground (Ctrl+C to stop)..."
    echo ""
    npm run dev
fi
